import questionsData from '../../public/assets/data/legal-questions.json';
import caseData from '../../public/assets/data/legal-case-data.json';

export interface LegalQuestion {
    id: number;
    section: string;
    question: string;
    answer: string;
}

// Legacy case data structure from JSON file
export const LEGAL_QUESTIONS: LegalQuestion[] = questionsData as LegalQuestion[];
export const CASE_DATA = caseData;

// Texas Case Law is now dynamically generated by AI based on specific case facts
// See: src/data/texas-case-law-archive.md for original hardcoded examples
